### PR TITLE
Angular 13

### LINKED ISSUE #8: Support for Angular 12
I wanted update version on angular to 12 so I've run the command:
```
ng update @angular/core@12 @angular/cli@12
```
It failed with message:
```
Package "safe-pipe" has an incompatible peer dependency to "@angular/platform-browser" (requires "~9.1.1" (extended), would install "12.1.4")
```

### PR DESCRIPTION
**Pull request by jethas-bennettjones**
Closes #8 and #6

- Upgrade to Angular 10
- Upgrade to Angular 11
- Upgrade to Angular 12
- Upgrade to Angular 13
- Fix build issue

### CODE REVIEW

**Comment by jethas-bennettjones** [comment]
@embarq

**Comment by embarq** [comment]
@jethas-bennettjones Thanks for the PR! Good job. I checked the changes and all looks good. I'll test and publish the new version later this weekend.

**Comment by jethas-bennettjones** [comment]
Let me know if you have any issues with merging this.

**Comment by embarq** [comment]
@jethas-bennettjones I've just merged this PR. Thanks for your work!

I'm going to publish new version on npm. What do you think should I bump the major or minor version? I don't have much practical knowledge with sem-ver 😞

**Comment by jethas-bennettjones** [comment]
@embarq Now might not be a bad time to publish a 1.0 release. 😄

**Comment by embarq** [comment]
@jethas-bennettjones appreciate your suggestion!

**Comment by sandrooco** [comment]
@embarq is there a release planned yet?
Thanks in advance!

**Pull request merged**
