### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by jethas-bennettjones**
Updated so that it's compatible with all 13.x.x releases and not just 13.1.x releases.

### CODE REVIEW

**Comment by jethas-bennettjones** [comment]
@embarq

**Comment by sandrooco** [comment]
Thanks for creating this PR!
This would fix #22.

**Comment by jethas-bennettjones** [comment]
@embarq Any update on this?

**Comment by mrbatista** [comment]
@embarq Please merge this PR and release new version.
Thanks

**Pull request merged**
